// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/joepk90/graphql-auth/internal/auth (interfaces: AuthorizerInterface)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../mocks/authorizer_mock.go github.com/joepk90/graphql-auth/internal/auth AuthorizerInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	auth "github.com/joepk90/graphql-auth/internal/auth"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthorizerInterface is a mock of AuthorizerInterface interface.
type MockAuthorizerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizerInterfaceMockRecorder
	isgomock struct{}
}

// MockAuthorizerInterfaceMockRecorder is the mock recorder for MockAuthorizerInterface.
type MockAuthorizerInterfaceMockRecorder struct {
	mock *MockAuthorizerInterface
}

// NewMockAuthorizerInterface creates a new mock instance.
func NewMockAuthorizerInterface(ctrl *gomock.Controller) *MockAuthorizerInterface {
	mock := &MockAuthorizerInterface{ctrl: ctrl}
	mock.recorder = &MockAuthorizerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizerInterface) EXPECT() *MockAuthorizerInterfaceMockRecorder {
	return m.recorder
}

// IsAllowed mocks base method.
func (m *MockAuthorizerInterface) IsAllowed(arg0 context.Context, arg1 auth.ActionOnResource) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAllowed", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAllowed indicates an expected call of IsAllowed.
func (mr *MockAuthorizerInterfaceMockRecorder) IsAllowed(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAllowed", reflect.TypeOf((*MockAuthorizerInterface)(nil).IsAllowed), arg0, arg1)
}
