// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/joepk90/graphql-auth/internal/stats (interfaces: Metrics)
//
// Generated by this command:
//
//	mockgen -package=mocks -destination=../mocks/metrics.go github.com/joepk90/graphql-auth/internal/stats Metrics
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// ObserveQuery mocks base method.
func (m *MockMetrics) ObserveQuery(queryType, method string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveQuery", queryType, method)
}

// ObserveQuery indicates an expected call of ObserveQuery.
func (mr *MockMetricsMockRecorder) ObserveQuery(queryType, method any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveQuery", reflect.TypeOf((*MockMetrics)(nil).ObserveQuery), queryType, method)
}

// ObserveQueryError mocks base method.
func (m *MockMetrics) ObserveQueryError(queryType, method string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveQueryError", queryType, method)
}

// ObserveQueryError indicates an expected call of ObserveQueryError.
func (mr *MockMetricsMockRecorder) ObserveQueryError(queryType, method any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveQueryError", reflect.TypeOf((*MockMetrics)(nil).ObserveQueryError), queryType, method)
}

// ObserveRequest mocks base method.
func (m *MockMetrics) ObserveRequest() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveRequest")
}

// ObserveRequest indicates an expected call of ObserveRequest.
func (mr *MockMetricsMockRecorder) ObserveRequest() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveRequest", reflect.TypeOf((*MockMetrics)(nil).ObserveRequest))
}

// ObserveRequestSize mocks base method.
func (m *MockMetrics) ObserveRequestSize(arg0 float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveRequestSize", arg0)
}

// ObserveRequestSize indicates an expected call of ObserveRequestSize.
func (mr *MockMetricsMockRecorder) ObserveRequestSize(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveRequestSize", reflect.TypeOf((*MockMetrics)(nil).ObserveRequestSize), arg0)
}

// ObserveResponseSize mocks base method.
func (m *MockMetrics) ObserveResponseSize(arg0 float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveResponseSize", arg0)
}

// ObserveResponseSize indicates an expected call of ObserveResponseSize.
func (mr *MockMetricsMockRecorder) ObserveResponseSize(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveResponseSize", reflect.TypeOf((*MockMetrics)(nil).ObserveResponseSize), arg0)
}

// ObserveResponseTime mocks base method.
func (m *MockMetrics) ObserveResponseTime(arg0 time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveResponseTime", arg0)
}

// ObserveResponseTime indicates an expected call of ObserveResponseTime.
func (mr *MockMetricsMockRecorder) ObserveResponseTime(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveResponseTime", reflect.TypeOf((*MockMetrics)(nil).ObserveResponseTime), arg0)
}
